name: MySQL Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up MySQL
      uses: mysql/setup-mysql@v2
      with:
        mysql-version: '5.7'
        root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    - name: Start MySQL Service
      run: sudo service mysql start

    - name: Check out code
      uses: actions/checkout@v2

    # Additional steps to run tests, migrations, or other database-related tasks

    - name: Clean up MySQL
      run: mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "DROP DATABASE IF EXISTS my_database"

    - name: Finalize
      run: echo "MySQL workflow completed successfully"

