name: MySQL Setup Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MySQL
      run: |
        sudo apt-get update -y
        sudo apt-get install -y mysql-server
        sudo systemctl start mysql
        sudo mysql_secure_installation
      env:
        MYSQL_ROOT_PASSWORD1: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    - name: Create a test database
      run: |
        mysql -u root --password=$MYSQL_ROOT_PASSWORD1 -e 'CREATE DATABASE testdb;'
